export type FallbackImage = {
  src: string;
  thumb: string;
  descriptionUrl?: string;
  credit?: string;
  license?: string;
  licenseUrl?: string;
};

export const fallbackImages: Record<string, FallbackImage> = {
  "Vaccinium myrtillus": {
    src: "https://upload.wikimedia.org/wikipedia/commons/5/5c/203_Vaccinum_myrtillus_L.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/203_Vaccinum_myrtillus_L.jpg/330px-203_Vaccinum_myrtillus_L.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:203_Vaccinum_myrtillus_L.jpg",
    credit: "Amédée Masclef",
    license: "Public domain",
    licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },
  "Vaccinium vitis-idaea": {
    src: "https://upload.wikimedia.org/wikipedia/commons/f/f1/Vaccinium_vitis-idaea_20060824_003.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Vaccinium_vitis-idaea_20060824_003.jpg/330px-Vaccinium_vitis-idaea_20060824_003.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Vaccinium_vitis-idaea_20060824_003.jpg",
    credit: "Jonas Bergsten",
    license: "Public domain",
    licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },
  "Vaccinium oxycoccos": {
    src: "https://upload.wikimedia.org/wikipedia/commons/4/4d/VacciniumOxycoccos.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/VacciniumOxycoccos.jpg/330px-VacciniumOxycoccos.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:VacciniumOxycoccos.jpg",
    credit: "Christian Fischer",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
  },
  "Hippophae rhamnoides": {
    src: "https://upload.wikimedia.org/wikipedia/commons/3/3a/Hippophae_rhamnoides-01_%28xndr%29.JPG",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Hippophae_rhamnoides-01_%28xndr%29.JPG/330px-Hippophae_rhamnoides-01_%28xndr%29.JPG",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Hippophae_rhamnoides-01_(xndr).JPG",
    credit: "No machine-readable author provided. Svdmolen assumed (based on copyright claims).",
    license: "CC BY-SA 3.0",
    licenseUrl: "http://creativecommons.org/licenses/by-sa/3.0/",
  },
  "Rubus arcticus": {
    src: "https://upload.wikimedia.org/wikipedia/commons/7/79/Rubus_arcticus.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Rubus_arcticus.jpg/330px-Rubus_arcticus.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Rubus_arcticus.jpg",
    credit: "Carl Axel Magnus Lindman",
    license: "Public domain",
    licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },
  "Cantharellus tubaeformis": {
    src: "https://upload.wikimedia.org/wikipedia/commons/0/08/Craterellus_tubaeformis_LC0374.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Craterellus_tubaeformis_LC0374.jpg/330px-Craterellus_tubaeformis_LC0374.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Craterellus_tubaeformis_LC0374.jpg",
    credit: "Jörg Hempel",
    license: "CC BY-SA 3.0 de",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
  },
  "Boletus edulis": {
    src: "https://upload.wikimedia.org/wikipedia/commons/3/34/Boletus_edulis_IT.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Boletus_edulis_IT.jpg/330px-Boletus_edulis_IT.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Boletus_edulis_IT.jpg",
    credit: "ReddishClover",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
  },
  "Cantharellus cibarius": {
    src: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Chanterelle_Cantharellus_cibarius.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Chanterelle_Cantharellus_cibarius.jpg/330px-Chanterelle_Cantharellus_cibarius.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Chanterelle_Cantharellus_cibarius.jpg",
    license: "CC BY-SA 3.0",
    licenseUrl: "http://creativecommons.org/licenses/by-sa/3.0/",
  },
  "Amanita virosa": {
    src: "https://upload.wikimedia.org/wikipedia/commons/8/81/Destroying_Angel_02.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Destroying_Angel_02.jpg/330px-Destroying_Angel_02.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Destroying_Angel_02.jpg",
    credit: "en:User:Ben DeRoy",
    license: "Public domain",
    licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },
  "Amanita muscaria": {
    src: "https://upload.wikimedia.org/wikipedia/commons/3/32/Amanita_muscaria_3_vliegenzwammen_op_rij.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Amanita_muscaria_3_vliegenzwammen_op_rij.jpg/330px-Amanita_muscaria_3_vliegenzwammen_op_rij.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Amanita_muscaria_3_vliegenzwammen_op_rij.jpg",
    credit: "Onderwijsgek",
    license: "CC BY-SA 3.0 nl",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/nl/deed.en",
  },
  "Lactarius torminosus": {
    src: "https://upload.wikimedia.org/wikipedia/commons/0/01/Lactarius_torminosus_%28cropped%29.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Lactarius_torminosus_%28cropped%29.jpg/330px-Lactarius_torminosus_%28cropped%29.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Lactarius_torminosus_(cropped).jpg",
    credit: "Tocekas",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
  },
  "Russula paludosa": {
    src: "https://upload.wikimedia.org/wikipedia/commons/8/8d/Tiny_Russula_paludosa_%28Appelrussula%29_at_Rozendaal_castle_park_-_panoramio.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Tiny_Russula_paludosa_%28Appelrussula%29_at_Rozendaal_castle_park_-_panoramio.jpg/330px-Tiny_Russula_paludosa_%28Appelrussula%29_at_Rozendaal_castle_park_-_panoramio.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Tiny_Russula_paludosa_(Appelrussula)_at_Rozendaal_castle_park_-_panoramio.jpg",
    credit: "Henk Monster",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0",
  },
  "Gyromitra esculenta": {
    src: "https://upload.wikimedia.org/wikipedia/commons/9/97/Fr%C3%BChjahrslorchel.JPG",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Fr%C3%BChjahrslorchel.JPG/330px-Fr%C3%BChjahrslorchel.JPG",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Fr%C3%BChjahrslorchel.JPG",
    license: "CC BY-SA 3.0",
    licenseUrl: "http://creativecommons.org/licenses/by-sa/3.0/",
  },
  "Craterellus cornucopioides": {
    src: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Craterellus_cornucopioides_JPG1.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Craterellus_cornucopioides_JPG1.jpg/330px-Craterellus_cornucopioides_JPG1.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Craterellus_cornucopioides_JPG1.jpg",
    credit: "Jean-Pol GRANDMONT",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0",
  },
  "Albatrellus ovinus": {
    src: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Albatrellus-ovinus.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Albatrellus-ovinus.jpg/330px-Albatrellus-ovinus.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Albatrellus-ovinus.jpg",
    credit: "Bernypisa",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
  },
  "Apple": {
    src: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Pink_lady_and_cross_section.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Pink_lady_and_cross_section.jpg/330px-Pink_lady_and_cross_section.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Pink_lady_and_cross_section.jpg",
    credit: "fir0002 flagstaffotos [at] gmail.com Canon 20D + Sigma 150mm f/2.8",
    license: "GFDL 1.2",
    licenseUrl: "http://www.gnu.org/licenses/old-licenses/fdl-1.2.html",
  },
  "Cherry": {
    src: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Cherry_season_%2848216568227%29.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Cherry_season_%2848216568227%29.jpg/330px-Cherry_season_%2848216568227%29.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Cherry_season_(48216568227).jpg",
    credit: "spurekar",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
  },
  "Plum": {
    src: "https://upload.wikimedia.org/wikipedia/commons/e/ec/Plums_African_Rose_-_whole%2C_halved_and_slice.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Plums_African_Rose_-_whole%2C_halved_and_slice.jpg/330px-Plums_African_Rose_-_whole%2C_halved_and_slice.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Plums_African_Rose_-_whole,_halved_and_slice.jpg",
    credit: "Ivar Leidus",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
  },
  "Pear": {
    src: "https://upload.wikimedia.org/wikipedia/commons/c/cf/Pears.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Pears.jpg/330px-Pears.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Pears.jpg",
    credit: "Keith Weller",
    license: "Public domain",
    licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },
  "Ribes uva-crispa": {
    src: "https://upload.wikimedia.org/wikipedia/commons/8/82/Ribes_uva-crispa_kz04.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Ribes_uva-crispa_kz04.jpg/330px-Ribes_uva-crispa_kz04.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Ribes_uva-crispa_kz04.jpg",
    credit: "Krzysztof Ziarnek, Kenraiz",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
  },
  "White currant": {
    src: "https://upload.wikimedia.org/wikipedia/commons/3/3d/Groseilles_blanches.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Groseilles_blanches.jpg/330px-Groseilles_blanches.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Groseilles_blanches.jpg",
    credit: "Marie-Lan Nguyen",
    license: "CC BY-SA 3.0",
    licenseUrl: "http://creativecommons.org/licenses/by-sa/3.0/",
  },
  "Garden strawberry": {
    src: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Garden_strawberry_%28Fragaria_%C3%97_ananassa%29_single2.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Garden_strawberry_%28Fragaria_%C3%97_ananassa%29_single2.jpg/330px-Garden_strawberry_%28Fragaria_%C3%97_ananassa%29_single2.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Garden_strawberry_(Fragaria_%C3%97_ananassa)_single2.jpg",
    credit: "Ivar Leidus",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
  },
  "Anethum graveolens": {
    src: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Illustration_Anethum_graveolens_clean.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Illustration_Anethum_graveolens_clean.jpg/330px-Illustration_Anethum_graveolens_clean.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Illustration_Anethum_graveolens_clean.jpg",
    credit: "Illustration_Anethum_graveolens0.jpg : Prof. Dr. Otto Wilhelm Thomé derivative work: Aroche ( talk )",
    license: "Public domain",
    licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },
  "Parsley": {
    src: "https://upload.wikimedia.org/wikipedia/commons/e/e4/Petroselinum.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Petroselinum.jpg/330px-Petroselinum.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Petroselinum.jpg",
    credit: "Jonathunder",
    license: "GFDL 1.2",
    licenseUrl: "http://www.gnu.org/licenses/old-licenses/fdl-1.2.html",
  },
  "Basil": {
    src: "https://upload.wikimedia.org/wikipedia/commons/9/97/Ocimum_basilicum_8zz.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Ocimum_basilicum_8zz.jpg/330px-Ocimum_basilicum_8zz.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Ocimum_basilicum_8zz.jpg",
    credit: "Photo by David J. Stang",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
  },
  "Allium schoenoprasum": {
    src: "https://upload.wikimedia.org/wikipedia/commons/4/49/Allium_schoenoprasum_-_Bombus_lapidarius_-_Tootsi.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Allium_schoenoprasum_-_Bombus_lapidarius_-_Tootsi.jpg/330px-Allium_schoenoprasum_-_Bombus_lapidarius_-_Tootsi.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Allium_schoenoprasum_-_Bombus_lapidarius_-_Tootsi.jpg",
    credit: "Ivar Leidus",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
  },
  "Spinacia oleracea": {
    src: "https://upload.wikimedia.org/wikipedia/commons/3/37/Spinacia_oleracea_Spinazie_bloeiend.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Spinacia_oleracea_Spinazie_bloeiend.jpg/330px-Spinacia_oleracea_Spinazie_bloeiend.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Spinacia_oleracea_Spinazie_bloeiend.jpg",
    credit: "Rasbak",
    license: "CC BY-SA 3.0",
    licenseUrl: "http://creativecommons.org/licenses/by-sa/3.0/",
  },
  "Mentha": {
    src: "https://upload.wikimedia.org/wikipedia/commons/4/4d/Mentha_spicata-IMG_6186.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Mentha_spicata-IMG_6186.jpg/330px-Mentha_spicata-IMG_6186.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Mentha_spicata-IMG_6186.jpg",
    credit: "C T Johansson",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
  },
  "Carrot": {
    src: "https://upload.wikimedia.org/wikipedia/commons/a/a2/Vegetable-Carrot-Bundle-wStalks.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Vegetable-Carrot-Bundle-wStalks.jpg/330px-Vegetable-Carrot-Bundle-wStalks.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Vegetable-Carrot-Bundle-wStalks.jpg",
    credit: "Evan-Amos",
    license: "Public domain",
    licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },
  "Potato": {
    src: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Patates.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Patates.jpg/330px-Patates.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Patates.jpg",
    credit: "Scott Bauer, USDA ARS",
    license: "Public domain",
    licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },
  "Beetroot": {
    src: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Detroitdarkredbeets.png",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Detroitdarkredbeets.png/330px-Detroitdarkredbeets.png",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Detroitdarkredbeets.png",
    credit: "BriannaWalther",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
  },
  "Radish": {
    src: "https://upload.wikimedia.org/wikipedia/commons/0/0c/Radish_3371103037_4ab07db0bf_o.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Radish_3371103037_4ab07db0bf_o.jpg/330px-Radish_3371103037_4ab07db0bf_o.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Radish_3371103037_4ab07db0bf_o.jpg",
    credit: "Self, en:User:Jengod",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
  },
  "Turnip": {
    src: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Turnip_2622027.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Turnip_2622027.jpg/330px-Turnip_2622027.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Turnip_2622027.jpg",
    credit: "thebittenword.com",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
  },
  "Parsnip": {
    src: "https://upload.wikimedia.org/wikipedia/commons/1/1f/Pastinaca_sativa_MHNT.BOT.2004.0.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Pastinaca_sativa_MHNT.BOT.2004.0.jpg/330px-Pastinaca_sativa_MHNT.BOT.2004.0.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Pastinaca_sativa_MHNT.BOT.2004.0.jpg",
    credit: "Didier Descouens",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
  },
  "Zucchini": {
    src: "https://upload.wikimedia.org/wikipedia/commons/9/92/CSA-Striped-Zucchini.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/CSA-Striped-Zucchini.jpg/330px-CSA-Striped-Zucchini.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:CSA-Striped-Zucchini.jpg",
    credit: "Evan-Amos",
    license: "Public domain",
    licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },
  "Lettuce": {
    src: "https://upload.wikimedia.org/wikipedia/commons/d/da/Iceberg_lettuce_in_SB.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Iceberg_lettuce_in_SB.jpg/330px-Iceberg_lettuce_in_SB.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Iceberg_lettuce_in_SB.jpg",
    credit: "en:User:Geographer",
    license: "CC BY 1.0",
    licenseUrl: "https://creativecommons.org/licenses/by/1.0",
  },
  "Cucumber": {
    src: "https://upload.wikimedia.org/wikipedia/commons/9/96/ARS_cucumber.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/ARS_cucumber.jpg/330px-ARS_cucumber.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:ARS_cucumber.jpg",
    credit: "Stephen Ausmus, USDA ARS",
    license: "Public domain",
    licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },
  "Rhubarb": {
    src: "https://upload.wikimedia.org/wikipedia/commons/2/2b/Rheum_rhabarbarum.2006-04-27.uellue.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Rheum_rhabarbarum.2006-04-27.uellue.jpg/330px-Rheum_rhabarbarum.2006-04-27.uellue.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Rheum_rhabarbarum.2006-04-27.uellue.jpg",
    credit: "Dieter Weber ( User:Uellue )",
    license: "CC BY-SA 3.0",
    licenseUrl: "http://creativecommons.org/licenses/by-sa/3.0/",
  },
  "Cabbage": {
    src: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Cabbage_and_cross_section_on_white.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Cabbage_and_cross_section_on_white.jpg/330px-Cabbage_and_cross_section_on_white.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Cabbage_and_cross_section_on_white.jpg",
    credit: "fir0002 flagstaffotos [at] gmail.com Canon 20D + Sigma 150mm f/2.8",
    license: "GFDL 1.2",
    licenseUrl: "http://www.gnu.org/licenses/old-licenses/fdl-1.2.html",
  },
  "Celery": {
    src: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Celery_1.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Celery_1.jpg/330px-Celery_1.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Celery_1.jpg",
    credit: "Lombroso",
    license: "Public domain",
    licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },
  "Eggplant": {
    src: "https://upload.wikimedia.org/wikipedia/commons/7/76/Solanum_melongena_24_08_2012_%281%29.JPG",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Solanum_melongena_24_08_2012_%281%29.JPG/330px-Solanum_melongena_24_08_2012_%281%29.JPG",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Solanum_melongena_24_08_2012_(1).JPG",
    credit: "Joydeep",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
  },
  "Coregonus albula": {
    src: "https://upload.wikimedia.org/wikipedia/commons/5/5b/Finnish_fried_vendace_%28Paistetut_muikut%29.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Finnish_fried_vendace_%28Paistetut_muikut%29.jpg/330px-Finnish_fried_vendace_%28Paistetut_muikut%29.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Finnish_fried_vendace_(Paistetut_muikut).jpg",
    credit: "V-7",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
  },
  "Baltic herring": {
    src: "https://upload.wikimedia.org/wikipedia/commons/0/04/Clupea_harengus.png",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/0/04/Clupea_harengus.png",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Clupea_harengus.png",
    credit: "Unknown author Unknown author",
    license: "Public domain",
    licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },
  "Perca fluviatilis": {
    src: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Barsche_im_See_%28Jungfische%29.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Barsche_im_See_%28Jungfische%29.jpg/330px-Barsche_im_See_%28Jungfische%29.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Barsche_im_See_(Jungfische).jpg",
    credit: "Dellex",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
  },
  "Atlantic salmon": {
    src: "https://upload.wikimedia.org/wikipedia/commons/8/82/Wst_atlantischer_lachs_stoer_001.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Wst_atlantischer_lachs_stoer_001.jpg/330px-Wst_atlantischer_lachs_stoer_001.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Wst_atlantischer_lachs_stoer_001.jpg",
    credit: "User:Wolfgang Striewski",
    license: "Public domain",
    licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },
  "Coregonus lavaretus": {
    src: "https://upload.wikimedia.org/wikipedia/commons/a/a1/Sik%2C_Iduns_kokbok.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Sik%2C_Iduns_kokbok.jpg/330px-Sik%2C_Iduns_kokbok.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Sik,_Iduns_kokbok.jpg",
    credit: "see Iduns kokbok",
    license: "Public domain",
    licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },
  "Esox lucius": {
    src: "https://upload.wikimedia.org/wikipedia/commons/9/93/Esox_lucius_ZOO_1.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Esox_lucius_ZOO_1.jpg/330px-Esox_lucius_ZOO_1.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Esox_lucius_ZOO_1.jpg",
    credit: "Jik jik",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
  },
  "Sander lucioperca": {
    src: "https://upload.wikimedia.org/wikipedia/commons/6/63/Sander_lucioperca_1.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Sander_lucioperca_1.jpg/330px-Sander_lucioperca_1.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Sander_lucioperca_1.jpg",
    credit: "eLNuko",
    license: "Public domain",
    licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },
  "Lota lota": {
    src: "https://upload.wikimedia.org/wikipedia/commons/1/14/Tr%C3%BCsche_Walchensee.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Tr%C3%BCsche_Walchensee.jpg/330px-Tr%C3%BCsche_Walchensee.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Tr%C3%BCsche_Walchensee.jpg",
    license: "CC BY-SA 3.0",
    licenseUrl: "http://creativecommons.org/licenses/by-sa/3.0/",
  },
  "Salvelinus alpinus": {
    src: "https://upload.wikimedia.org/wikipedia/commons/f/f2/Salvelinus_alpinus_311639131.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Salvelinus_alpinus_311639131.jpg/330px-Salvelinus_alpinus_311639131.jpg",
    descriptionUrl: "https://commons.wikimedia.org/wiki/File:Salvelinus_alpinus_311639131.jpg",
    credit: "Alison Copeland",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
  },
};